# Generated by Django 3.0 on 2021-04-05 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    initial = True

    dependencies = [
        ('cadastro', '0002_auto_20210405_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda_receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=194, verbose_name='Nome completo')),
                ('data_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Data de inicio para tomar o remédio')),
                ('data_termino', models.DateTimeField(blank=True, null=True, verbose_name='Data do termino para tomar o remédio')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluido')),
                ('reajuste', models.BooleanField(default=False, verbose_name='Reajuste')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Receita', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Agenda da receita',
                'verbose_name_plural': 'Agenda das receitas',
                'db_table': 'agenda_receita',
            },
        ),
        migrations.CreateModel(
            name='Horario_remedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(blank=True, null=True, verbose_name='Horario para tomar remédio')),
                ('concluido', models.BooleanField(default=False, verbose_name='Concluido')),
                ('agenda_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm_remedio.Agenda_receita', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Horário do remédio',
                'verbose_name_plural': 'Horários do remédio',
                'db_table': 'horário_remedio',
            },
        ),
    ]
