# Generated by Django 3.0 on 2021-04-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm_remedio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda_receita',
            name='nome_completo',
        ),
    ]
