# Generated by Django 3.0 on 2021-03-31 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=194, verbose_name='Nome completo')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(blank=True, max_length=194, null=True, unique=True, verbose_name='E-mail')),
                ('horario_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Horário de criação')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='Remedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=194, verbose_name='Nome completo')),
                ('descricao', models.TextField(max_length=350, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Remedio',
                'verbose_name_plural': 'Remedios',
                'db_table': 'remedio',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervalo', models.FloatField(default=0, verbose_name='Intervalo de tempo')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de inicio para tomar o remédio')),
                ('dosagem', models.FloatField(default=0, verbose_name='Dosagem do Remédio')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Pessoa', verbose_name='Nome do paciente')),
                ('remedio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Remedio', verbose_name='Nome do remedio')),
            ],
        ),
    ]
