# Generated by Django 3.0 on 2021-04-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('cadastro', '0004_auto_20210405_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Usuário está ativo'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Usuário é da equipe de desenvolvimento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Usuário é um superusuario'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='password',
            field=models.CharField(default=1, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
