# Generated by Django 3.0 on 2021-04-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20210405_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=194, null=True, verbose_name='Nome completo'),
        ),
    ]
