# Generated by Django 3.0 on 2021-04-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_auto_20210405_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='quantidade_dias',
            field=models.IntegerField(default=0, help_text='total de dias que será consumido o remédio', verbose_name='Total de dias'),
        ),
    ]
