# Generated by Django 3.0 on 2021-04-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_receita_quantidade_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='quantidade_dias',
            field=models.PositiveIntegerField(default=0, help_text='total de dias que será consumido o remédio', verbose_name='Total de dias'),
        ),
    ]
